version: "2"

services:
  was:
    image: ${REGISTRY_URL}/${PROJECT_NAME}
    extends: 
      file: common-services.yml
      service: webapp
    environment:
    - "system.upload.handler=nginx"
    restart: "unless-stopped"

  httpd:
    extends: 
      file: common-services.yml
      service: httpd
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - $SSL_CERT:/usr/share/nginx/ssl/nginx.crt
    - $SSL_KEY:/usr/share/nginx/ssl/nginx.key
    ports:
    - "${HTTP_PORT}:80"
    depends_on: 
    - was
    restart: "unless-stopped"

  upload:
    extends: 
      file: common-services.yml
      service: upload
    restart: "unless-stopped"

  php:
    extends: 
      file: common-services.yml
      service: php
    restart: "unless-stopped"

volumes:
  tmp:
  thumb:
  ngx:
  app: